### ISSUE TITLE
csvReadFn doesn't work with functions like readr::read_csv()

### ISSUE THREAD

**Issue by andburch** [JimMcL/trajr#1]
Internally, csvReadFn is automatically called with the "stringsAsFactors = FALSE" as an argument, an argument which isn't universal to CSV-reading functions: it only works with utils::read.csv() and utils::read.csv2().
With the tidyverse "readr" package, read_csv() doesn't have "stringsAsFactors" as an accepted argument, so when the internal ` coordList <- csvReadFn(fileName, stringsAsFactors = FALSE)` runs, I get an error. I had to make a wrapper function for read_csv() that accepted the "stringsAsFactors" argument and never used it.

**Comment by andburch** [comment]
Also, this is pretty much the first "Issue" comment I've made on Git, so huzzah! Learning new things.

**Comment by JimMcL** [comment]
Modified so it now works with functions such as `readr::read_csv()`, and documentation adjusted accordingly.
