### ISSUE TITLE
TrajsBuild *doesn't* have the option of not smoothing trajectories

### ISSUE THREAD

**Issue by andburch** [JimMcL/trajr#2]
The function is described as: `Reads multiple trajectories from files, performs some basic sanity checks on them, and optionally smooths and scales them. Attempts to collect and report errors for multiple trajectories in a single call.`
However, although ` smoothP = 3, smoothN = 41,` are changeable smoothing parameters, you can't actually set these to zero or give TrajsBuild() the command to NOT apply smoothing.

**Comment by JimMcL** [comment]
Specify `smoothP = NA, smoothN` to apply no smoothing. I have updated the documentation to mention this.
