### ISSUE TITLE
3D

### ISSUE THREAD

**Issue by yakir12** [JimMcL/trajr#3]
Would be very useful!

**Comment by Foztarz** [comment]
Here too.

**Comment by JimMcL** [comment]
I agree 3D could be useful, however it is difficult to implement, so it won't happen anytime soon.
Issues that would need to be addressed:
* Internally, complex numbers are often used to represent coordinates, but they are strictly 2-dimensional.
* To what extent do the concepts addressed by `trajr` extend from 2D to 3D?

Constructive suggestions about what functionality would be useful for 3D trajectory analysis may increase the likelihood of it happening ;-)

**Comment by schienstockd** [comment]
I just discovered your package.

We are looking at 3D movement of cells within tissues. For us it would be useful to disinguish between a random or directed walk and a walk where cells seem to stop and look for something. This is related to Figure 2 in your paper.

This would be good to have in 3D. I have the coordinates as X,Y,Z coordinates in micron.

**Comment by JimMcL** [comment]
Limited 3D functionality has now been implemented. All functions specific to 3D trajectories are prefixed with "Traj3D". The vignette contains a brief introduction
